export default Object.freeze({
  Login: 'Login',
  Register: 'Register',
  HomeNavigator: 'HomeNavigator',
  Home: 'Home',
  Post: 'Post',
  Calendar: 'Calendar',
  CalendarScreen: 'CalendarScreen',
  Achievement: 'Achievement',
  AchievementList: 'AchievementList',
  Organization: 'Organization',
  OrganizationList: 'OrganizationList',
  OrganizationDetails: 'OrganizationDetails',
  Team: 'Team',
  TeamList: 'TeamList',
  CreateTeam: 'CreateTeam',
});
